title : 淘小僧
tagline: taoxiaoseng programing ios
author :
  name : taoxiaoseng
  email : taoxiaoseng@gmail.com
  github : taoxiaoseng
  twitter : taoxiaoseng
  feedburner : taoxiaoseng

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
